spring.application.name=ebdv-fdv

# Configuracon de la base de datos PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ebdv_fdv_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:ferchofrias}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Habiliar la recarga de Thymeleaf en desarrollo
spring.thymeleaf.cache=${THYMELEAF_CACHE:false}

# CONFIGURACIÓN DE SEGURIDAD (Login de la App)
app.security.admin.user=${ADMIN1_EMAIL:admin@local.com}
app.security.admin.pass=${ADMIN1_PASSWORD:claveLocal1}

app.security.maestro.user=${MAESTRO1_EMAIL:maestro@local.com}
app.security.maestro.pass=${MAESTRO1_PASSWORD:claveLocal2}

server.port=${PORT:8080}
